# SPDX-License-Identifier: Apache-2.0
"""Public re-exports for the Harbor exception hierarchy."""

from harbor.errors._hierarchy import (
    AdapterFallbackError,
    ArtifactNotFound,
    ArtifactStoreError,
    BroadcasterOverflow,
    CapabilityError,
    CheckpointError,
    ConsolidationRuleError,
    EmbeddingModelHashMismatch,
    FactConflictError,
    HarborError,
    HarborRuntimeError,
    IncompatibleEmbeddingHashError,
    IncompatibleMigrationError,
    IncompatibleModelHashError,
    IncompatibleSchemaError,
    IncompatibleSklearnVersion,
    IRValidationError,
    MemoryScopeError,
    MigrationNotSupported,
    MLNodeError,
    NamespaceConflictError,
    PackCompatError,
    PackSignatureError,
    PluginLoadError,
    ProfileViolationError,
    ReplayError,
    SimulationError,
    StoreError,
    UnportableCypherError,
    ValidationError,
)

__all__ = [
    "AdapterFallbackError",
    "ArtifactNotFound",
    "ArtifactStoreError",
    "BroadcasterOverflow",
    "CapabilityError",
    "CheckpointError",
    "ConsolidationRuleError",
    "EmbeddingModelHashMismatch",
    "FactConflictError",
    "HarborError",
    "HarborRuntimeError",
    "IRValidationError",
    "IncompatibleEmbeddingHashError",
    "IncompatibleMigrationError",
    "IncompatibleModelHashError",
    "IncompatibleSchemaError",
    "IncompatibleSklearnVersion",
    "MLNodeError",
    "MemoryScopeError",
    "MigrationNotSupported",
    "NamespaceConflictError",
    "PackCompatError",
    "PackSignatureError",
    "PluginLoadError",
    "ProfileViolationError",
    "ReplayError",
    "SimulationError",
    "StoreError",
    "UnportableCypherError",
    "ValidationError",
]
