# SPDX-License-Identifier: Apache-2.0
"""Auto-generated by Shipwright. Source of truth: shipwright-spec.md."""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel

from harbor.ir import Mirror


class State(BaseModel):
    input: Annotated[str, Mirror()] | None = None
